apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: backend
          image: samita7/todo-backend:latest
          imagePullPolicy: Always
          ports:
            - name: backend-port
              containerPort: 5000
              protocol: TCP
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: PORT
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: MONGODB_URI
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: todo-backend
spec:
  selector:
    app: todo-backend
  ports:
  - name: backend-port
    protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP

              