name: CI/CD Pipeline

on:
  pull_request:
    paths: ['server/**', 'client/**']

  push:
    branches: [main]
    paths: ['server/**', 'client/**']
  workflow_dispatch:  

env:
  DOCKER_USER: samita7
  BACKEND_IMAGE: todo-backend
  FRONTEND_IMAGE: todo-frontend

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # --- STAGE 1: QUALITY GATE (TEST) ---
  test-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Backend Test
        run: |
          cd server
          npm install

      - name: Run Frontend Test
        run: |
          cd client
          npm install

  # --- STAGE 2: BUILD & PUSH TO DOCKER HUB ---
  build-and-push:
    needs: test-stage
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: samita7
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ env.DOCKER_USER }}/${{ env.BACKEND_IMAGE }}:latest

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ${{ env.DOCKER_USER }}/${{ env.FRONTEND_IMAGE }}:latest

  # --- STAGE 3: DEPLOY ---
  # deploy:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Deploy on server via SSH
  #       uses: appleboy/ssh-action@v1
  #       with:
  #         host: ${{ secrets.SERVER_HOST }}
  #         username: ${{ secrets.SERVER_USER }}
  #         key: ${{ secrets.SSH_KEY }}
  #         script: |
  #           docker-compose pull
  #           docker-compose up -d --force-recreate

